ibm-granite-community/granite-snack-cookbook

- .gitignore
- README.md
- recipes/RAG/RAG_with_Langchain.ipynb
[#137](https://github.com/ibm-granite-community/pm/issues/137)
- Move RAG_with_Langchain over from granite-legal-cookbook repo
> Add snack: RAG_with_Langchain

- recipes/RAG/RAG_with_Langchain.ipynb
[#16](https://github.com/ibm-granite-community/granite-kitchen/issues/16)
- Add special deps for RAG
> Slim Kitchen - Snacks

- recipes/Summarize/Summarize.ipynb
1. Enabled scrolling for pip install cell output. 
2. Deleted a duplicate "has" in a print statement.
> Minor changes.

- recipes/RAG/RAG_with_Langchain.ipynb
- recipes/Summarize/Summarize.ipynb
[#147](https://github.com/ibm-granite-community/pm/issues/147):
- Use Prompt Guide format for prompts in RAG_with_Langchain recipe
- Use Prompt Guide format for prompts in Summarize recipe
> 147 Optimize Prompts

- recipes/Entity-Extraction/granite-8b-replicate-entity-books.ipynb
- Small text mods
- add Book class instantiation
> Entity Extraction - Fayvor's Edits

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
- README.md
- recipes/Entity-Extraction/entity_extraction.ipynb
> Entity Extraction New Branch

- recipes/Entity-Extraction/entity_extraction.ipynb
> Fix after running using deployed model

- recipes/RAG/RAG_with_Langchain.ipynb
> Fix typo in RAG_with_Langchain.ipynb

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
> fix HAP path

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
> Fix Guardian test in CI Workflow

- recipes/Function-Calling/Function_Calling.ipynb
The weather API used in this tutorial changed its required input formatting so that has been updated. Also, updated the tokenizer to the new 3.0 model.
- [*] **Commits signed**: All commits must be GPG or SSH signed.
- [*] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.
- [*] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [*] **Test locally**:
- [*] Ensure the code works in a fresh Python virtual environment (venv).
> Change tokenizer & change weather api request

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
> Turn off Agentic_RAG tests

- recipes/Entity-Extraction/entity_extraction.ipynb
- Refine prompt
- Catch json parsing and key errors
> Entity Extraction - catch model output parsing errors

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
- recipes/AI-Agents/Agentic_RAG.ipynb
- Pip install packages together
- Add bs4
> Get Agentic_RAG to run reliably on Python 3.10

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
- Set GRANITE_TESTING var in CI workflow
> Use GRANITE_TESTING in CI

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
- recipes/Function-Calling/Function_Calling.ipynb
#35:
- Use langchain-ibm WatsonXLLM to access model
- Trim down WatsonX instructions and point to Getting Started recipe
> Refactor Function_Calling to use Langchain WatsonX client

- .github/notebook_lists/vanilla_notebooks.txt
- .github/workflows/vanilla_workflow.yaml
- Comment out tests for Agentic_RAG and Function_Calling
> Don't test WatsonX

- recipes/AI-Agents/Agentic_RAG.ipynb
- recipes/Entity-Extraction/entity_extraction.ipynb
- recipes/Function-Calling/Function_Calling.ipynb
- recipes/RAG/RAG_with_Langchain.ipynb
- recipes/Summarize/Summarize.ipynb
[#152](https://github.com/ibm-granite-community/pm/issues/152)
- Replace granite-kitchen with utils install in recipes.
> Snacks - Install Utils instead of Kitchen

- recipes/RAG/RAG_with_Langchain.ipynb
[#152](https://github.com/ibm-granite-community/pm/issues/152)
- Add missing langchain-community install
> Fix langchain-community install

- .github/workflows/pdl_workflow.yaml
- .github/workflows/vanilla_workflow.yaml
> Removed "set -e", which is not necessary.

- recipes/Fine_Tuning/Finetuning_Granite_Pirate_Style.ipynb
Addresses #58 by setting the seed. Run twice in colab, identical output.
> Set Seed Closes #58

- .github/notebook_lists/vanilla_notebooks.txt
- recipes/AI-Agents/Agentic_RAG.ipynb
- recipes/Function-Calling/Function_Calling.ipynb
> enable two wx-based recipes

- .github/workflows/notebooks.yaml
Add a workflow_dispatch workflow to test PRs using secrets
> ci: Add support for testing a PR via a workflow_dispatch

- recipes/Fine_Tuning/Finetuning_Granite_Pirate_Style.ipynb
When saving/loading a model, either from huggingface or disk, it should work now.
> Saving LoRA

- README.md
> Table of Contents: whitespace, link order, section headers

- .github/notebook_lists/vanilla_notebooks.txt
- README.md
- recipes/Granite_Guardian/Granite_Guardian_Watsonx_Usage.ipynb
> Add granite guardian examples using watsonx

- .github/actions/ollama-setup/action.yml
- .github/dependabot.yml
- .github/notebook_lists/ollama_notebooks.txt
- .github/workflows/notebooks.yaml
- .pre-commit-config.yaml
- README.md
- recipes/Intrinsics/.gitignore
- recipes/Intrinsics/Granite_RAG_LoRA.ipynb
- recipes/Intrinsics/Granite_RAG_LoRA_HF.ipynb
Includes Ollama version and HF version.
> Recipes for Granite RAG 3.0 8b LoRA adapter

- README.md
> Fix cookbook name in readme

- .github/notebook_lists/vanilla_notebooks.txt
- README.md
- recipes/RAG/Granite_Docling_RAG.ipynb
> RAG with Docling using hosted Granite through Replicate

- recipes/Invoice-Extraction/Granite_Recipes_Invoices.ipynb
We use the main repo for the source of the invoice PDFs.
> Cleanup new invoice extraction recipe

- recipes/Summarize/Summarize.ipynb
We use the 3.1 model also the 3.1 model chat template to provide the documents to summarize.
Docling is now used to parse the book from HTML form and chunk it into chapters for summarization.
Fixes #80
> summarize: Update for Granite 3.1

- recipes/RAG/Granite_Docling_RAG.ipynb
Some text and code updates to tidy up the recipe.
> Updates to docling RAG recipe

- recipes/PDL/Prompt_Declaration_Language.ipynb
- recipes/PDL/Prompt_Declaration_Language_python.ipynb
> Update PDL recipes to use Granite 3.1

- recipes/AI-Agents/travel_planner_agent.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Detailed_Guide.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Quick_Start.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Usage_Governance_Workflow.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Watsonx_Usage.ipynb
> Update recipes for granite 3.1

- .github/notebook_lists/vanilla_notebooks.txt
- .gitignore
- README.md
- recipes/Evaluation/Unitxt_Demo_Strategies.ipynb
- recipes/Evaluation/Unitxt_Granite_as_Judge.ipynb
- recipes/Evaluation/Unitxt_Quick_Start.ipynb
Model evaluation notebooks powered by [unitxt](https://www.unitxt.ai) showing three use cases: running an existing dataset, evaluating different shot strategies, and using Granite as judge.
> Model Evaluation Notebooks

- recipes/RAG/Granite_Docling_RAG.ipynb
> tidy and typo fix

- recipes/Entity-Extraction/entity_extraction.ipynb
We use the granite chat template to create the prompts.
> entity extraction: Bug fixes and improvements

- recipes/Fine_Tuning/Finetuning_Granite_Pirate_Style.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Detailed_Guide.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Watsonx_Usage.ipynb
- recipes/Granite_Guardian/HAP.ipynb
- recipes/Load_LoRA_from_Huggingface/Load_LoRA_From_Huggingface.ipynb
> Gg add agentic risk

- recipes/AI-Agents/travel_planner_agent.ipynb
- [ X] **Commits signed**: All commits must be GPG or SSH signed.
- [X ] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.
> Fix typo in travel_planner_agent.ipynb

- .github/notebook_lists/vanilla_notebooks.txt
- README.md
- recipes/RAG/Granite_Multimodal_RAG.ipynb
> Multimodal RAG recipe

- recipes/RAG/Granite_Multimodal_RAG.ipynb
> Small tweaks to mmrag recipe

- recipes/RAG/Granite_Docling_RAG.ipynb
> docling rag: Update to use granite chat template

- recipes/Contract-Analysis/Granite_Recipes_Contracts_Analysis.ipynb
- recipes/Intrinsics/Granite_RAG_LoRA.ipynb
- recipes/Intrinsics/Granite_RAG_LoRA_HF.ipynb
- recipes/RAG/Granite_Docling_RAG.ipynb
- recipes/RAG/Granite_Multimodal_RAG.ipynb
- recipes/Summarize/Summarize.ipynb
Docling changed the name of the GitHub organization as part of the contribution to LF.
> Update docling URL

- recipes/Summarize/Summarize.ipynb
> Use utils wrap_text method to wrap the wide text output of the model

- README.md
> Update readme for the new RAG intrinsics recipe

- recipes/Evaluation/Unitxt_Demo_Strategies.ipynb
- recipes/Evaluation/Unitxt_Granite_as_Judge.ipynb
- recipes/Evaluation/Unitxt_Quick_Start.ipynb
> Fix evaluation notebooks to use latest granite models directly on Replicate

- recipes/Intrinsics/Granite_Reasoning.ipynb
> Update reasoning recipe for Granite 3.3

- recipes/Intrinsics/Granite_Reasoning.ipynb
Granite 3.3 is now linked to the deployment.
> Update model path to remove sha

- recipes/Granite_Guardian/Granite_Guardian_Detailed_Guide.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Quick_Start.ipynb
- recipes/Granite_Guardian/Granite_Guardian_Usage_Governance_Workflow.ipynb
> Update for guardian 3.2 release

- .github/workflows/notebooks.yaml
> Update harden-runner config

- constraints.txt
This can be helpful when a dependency has a version with problems.
> Support a centrally managed constraints file for pip installs

- constraints.txt
> Update constraints.txt for pymilvus 2.5.8 release

- README.md
> docs: link fixing for llamafactory fine tuning

- recipes/RAG/Inference_Scaling_RAG.ipynb
SEO improvements to inference scaling RAG recipe
> SEO improvements to inference scaling RAG recipe

- recipes/Summarize/Summarize.ipynb
> Extract prompt_template creation out of method

- README.md
- recipes/PDL/README.md
> Updated README docs to pass pre-commit tests

- .github/workflows/notebooks.yaml
- recipes/AI-Agents/github_agent.ipynb
- recipes/Intrinsics/Granite_RAG_LoRA_HF.ipynb
- recipes/RAG/Granite_Docling_RAG.ipynb
- recipes/RAG/Granite_Multimodal_RAG.ipynb
- recipes/RAG/Inference_Scaling_RAG.ipynb
- recipes/RAG/RAG_with_Langchain.ipynb
We remove 3.10 since some recipe notebooks have dependencies which require 3.11+.
> Remove python 3.10 from CI testing

- recipes/Tool-Calling/.gitignore
- recipes/Tool-Calling/Automatic_Tool_Calling.ipynb
Update Automatic Tool Calling with SEO-Optimized Markdown. Added more tools to improve performance of chess agent.
- [ X Ensure the code works in a fresh Python virtual environment (venv).
> Update Automatic Tool Calling Markdown, and Add New Tools for Chess Agent

- recipes/Intrinsics/Granite_RAG_LoRA_HF.ipynb
- recipes/RAG/Granite_Docling_RAG.ipynb
- recipes/RAG/Granite_Multimodal_RAG.ipynb
- recipes/RAG/Inference_Scaling_RAG.ipynb
- recipes/RAG/RAG_with_Langchain.ipynb
> Must now install milvus-lite to use a local Milvus DB

- recipes/Entity-Extraction/entity_extraction.ipynb
- recipes/RAG/Granite_Docling_RAG.ipynb
- recipes/RAG/Granite_Multimodal_RAG.ipynb
- recipes/RAG/Inference_Scaling_RAG.ipynb
- recipes/RAG/RAG_with_Langchain.ipynb
- recipes/Summarize/Summarize.ipynb
> Use chat completion models

- recipes/Entity-Extraction/entity_extraction.ipynb
- recipes/RAG/Granite_Docling_RAG.ipynb
- recipes/RAG/Granite_Multimodal_RAG.ipynb
- recipes/RAG/Inference_Scaling_RAG.ipynb
- recipes/RAG/RAG_with_Langchain.ipynb
- recipes/Summarize/Summarize.ipynb
> Update to Granite 4 model

- recipes/Entity-Extraction/entity_extraction.ipynb
- recipes/RAG/Inference_Scaling_RAG.ipynb
- recipes/Summarize/Summarize.ipynb
> Update for Granite 4's recommended temperature
